"""User sign of tariner , Booking add fee

Revision ID: 4460dc548aba
Revises: 832fae1e2e11
Create Date: 2025-07-24 14:45:00.300858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4460dc548aba'
down_revision: Union[str, Sequence[str], None] = '832fae1e2e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('fee', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_trainer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_trainer')
    op.drop_column('bookings', 'fee')
    # ### end Alembic commands ###
