"""Add sign of cancel booking

Revision ID: 832fae1e2e11
Revises: a1dbb799087c
Create Date: 2025-07-20 18:40:34.268133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832fae1e2e11'
down_revision: Union[str, Sequence[str], None] = 'a1dbb799087c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('signCancel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'signCancel')
    # ### end Alembic commands ###
