"""Add in court reactivating

Revision ID: a1dbb799087c
Revises: 3ca21f1606b0
Create Date: 2025-07-15 14:55:51.058583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dbb799087c'
down_revision: Union[str, Sequence[str], None] = '3ca21f1606b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courts', sa.Column('reactivate_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courts', 'reactivate_at')
    # ### end Alembic commands ###
